name: "Ragas LLM Evaluation Framework"
description: "Automated evaluation framework for LLMs using Ragas"

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Manual trigger

jobs:
  evaluate:
    runs-on: ubuntu-latest
    environment: evaluation

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Configure environment
      run: |
        # Copy .env template and set dummy values for testing
        cp .env .env.local
        echo "OPENAI_API_KEY=dummy_key" >> .env.local
        echo "AZURE_OPENAI_API_KEY=dummy_key" >> .env.local
        echo "AZURE_OPENAI_ENDPOINT=https://dummy.openai.azure.com/" >> .env.local
        echo "AZURE_OPENAI_API_VERSION=2024-02-01" >> .env.local
        echo "AZURE_OPENAI_DEPLOYMENT_NAME=dummy-deployment" >> .env.local

    - name: Run tests
      run: |
        pytest tests/ -v --tb=short
      env:
        PYTHONPATH: ${{ github.workspace }}

    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results
        path: |
          **/test-results.xml
          **/coverage.xml